name: Deployment
on:
  push:
    branches: [master]
jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: yarn build

      - name: Deploy site
        run: bash ./.github/workflows/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
